{
 "title": "FreeNAS 11 (Graphite data source)",
 "description": "FreeNAS 11 dashboard using Graphite data source",
 "tags": [ "OK" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "FreeNAS Server", "query": "servers.*" },
   { "name": "network_interface", "label": "Network Interface", "query": "servers.$server.interface-*" },
   { "name": "cpu", "label": "CPU", "query": "servers.$server.cpu-*" },
   { "name": "disk", "label": "Disk", "query": "servers.$server.disk-*" },
   { "name": "mount", "label": "Mount", "query": "servers.$server.df-*" }
  ]
 },
 "panels": [
  {
   "title": "Load 1min",
   "type": "singlestat",
   "description": "Quicknum, Load 1min",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "aliasByNode(servers.$server.load.load.shortterm,1,3)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime as an easily readable number",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.uptime.uptime"
    }
   ]
  },
  {
   "title": "ZFS ARC Hit Ratio",
   "type": "singlestat",
   "description": "Quicknum, Load 1min",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "aliasByNode(servers.$server.zfs_arc_v2.arcstat_ratio_arc-hits, 1)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "System Load",
   "type": "graph",
   "description": "1, 5 and 15 minute average load. Basically number of processes that have wanted to run per second with some averaging and decay to show load history.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$server.load.*.*, 1,4)"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "description": "CPU temperatures in Celsius",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(offset(servers.$server.cputemp-$cpu.*,-2731.5),0.1),1,2)"
    }
   ]
  },
  {
   "title": "ZFS ARC Hit Ratio",
   "type": "graph",
   "description": "ARC is ZFS in-memory cache, hit ratio should be between 90-100%. If not, you may need more memory.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$server.zfs_arc_v2.arcstat_ratio_arc-hits, 1)"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "graph",
   "description": "Time between reboots",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$server.uptime.uptime,1)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU Usage per CPU. Max is 100% or 100% times number of CPUs depending on FreeNAS setting System -> Advanced -> Report CPU usage in percentage. If your number is >100,  set that flag in FreeNAS.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$server.cpu-$cpu.*,1,3)"
    }
   ]
  },
  {
   "title": "Aggregation CPU Average",
   "type": "graph",
   "description": "CPU Usage across all CPUs. Max is 100% or 100% times number of CPUs(?) depending on FreeNAS setting System -> Advanced -> Report CPU usage in percentage. If your number is >100,  set that flag in FreeNAS.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.aggregation-cpu-average.*,1,3)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "description": "Number of processes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$server.processes.*,1,3)"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "description": "Swap on system",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.swap.swap-used"
    },
    { "target": "servers.$server.swap.swap-free" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Wired memory is kernel usage and will be very high because ZFS runs in kernel space and its cache etc is included in this number.  Default ZFS usage is 80% of total mem, configurable but leave it.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$server.memory.*,1,3)"
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "graph",
   "description": "Number of network packets",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.interface-$network_interface.if_packets.tx,1,2,4)"
    },
    {
     "target": "scale(aliasByNode(servers.$server.interface-$network_interface.if_packets.rx,1,2,4),-1)"
    }
   ]
  },
  {
   "title": "Network bytes",
   "type": "graph",
   "description": "Network R/W bytes per second",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.interface-$network_interface.if_octets.tx,1,2,4)"
    },
    {
     "target": "scale(aliasByNode(servers.$server.interface-$network_interface.if_octets.rx,1,2,4),-1)"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "description": "Network R/W Errors. Should not happen.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.interface-$network_interface.if_errors.*,1,2,4)"
    },
    {
     "target": "scale(aliasByNode(servers.$server.interface-$network_interface.if_errors.*,1,2,4),-1)"
    }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk percent busy",
   "type": "graph",
   "description": "How much of the time does the disk have a request active or pending",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$server.geom_stat.geom_busy_percent-$disk,1,3)"
    }
   ]
  },
  {
   "title": "Disk Operations/s (?)",
   "type": "graph",
   "description": "Unsure what this is exactly since there is a RWD metric on the same.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_ops-$disk,1,3)"
    }
   ]
  },
  {
   "title": "Disk RWD Operations/s (?)",
   "type": "graph",
   "description": "Unsure what this exactly",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_ops_rwd-$disk.*,1,3)"
    }
   ]
  },
  {
   "title": "Disk Bandwidth(?)",
   "type": "graph",
   "description": "Unsure what BW means here,  potentially bandwidth i.e. number of Bytes/s",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_bw-$disk.*,1,3)"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "How long does the disk time to fulful a request",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_latency-$disk.*,1,3,4)"
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "graph",
   "description": "How many disk requests are there in the queue",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_queue-$disk,1,3)"
    }
   ]
  },
  {
   "title": "Disk Temperatures",
   "type": "graph",
   "description": "Disk temperatures. Not all disks/controllers will report this.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.disktemp-$disk.temperature,1,2)"
    }
   ]
  },
  {
   "title": "Filesystem Free",
   "type": "graph",
   "description": "Available memory on all filesystems",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(servers.$server.df-$mount.df_complex-free,1,2)"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "description": "Lists free, reserved and used space on available filesystems",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.df-$mount.*,1,2,3)"
    }
   ]
  },
  { "title": "Technical details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CTL IOCTL",
   "type": "graph",
   "description": "CTL - CAM Target Layer stuff",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.ctl-ioctl.*.*"
    }
   ]
  },
  {
   "title": "CTL TPC",
   "type": "graph",
   "description": "CTL - CAM Target Layer stuff",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.ctl-tpc.*.*"
    }
   ]
  },
  {
   "title": "ZFS ARC complete",
   "type": "graph",
   "description": "All the ZFS ARC (in-memory ZFS cache) in one place",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.zfs_arc.*"
    }
   ]
  },
  {
   "title": "ZFS ARC v2 complete",
   "type": "graph",
   "description": "All the ZFS ARC v2 measurements in one place.  Unsure if this is newer or complimentary to the ZFS ARC measurements.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.zfs_arc_v2.*"
    }
   ]
  }
 ]
}